---
- hosts: "*"
  become: yes
  tasks:
    - name: Check
      ansible.builtin.shell:
        cmd: dpkg --get-selections | grep hold | wc -l
        register: reboot_required
        ignore_errors: true
    - name: Reboot
      ansible.builtin.reboot:
        msg: Rebooting for apt updates
        when: reboot_required.stdout != '0'
