---
- name: reboot module
  hosts: "*"
  become: true
  tasks:
    - name: reboot host(s)
      ansible.builtin.reboot:
        msg: "rebooted by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
